"""messages table

Revision ID: bcb99d625478
Revises: 
Create Date: 2026-02-15 22:18:06.654149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcb99d625478"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        INSERT INTO message (id, text) VALUES
            (1, 'Text mock 1'),
            (2, 'Text mock 2'),
            (3, 'Text mock 3'),
            (4, 'Text mock 4'),
            (5, 'Text mock 5'),
            (6, 'Text mock 6'),
            (7, 'Text mock 7'),
            (8, 'Text mock 8'),
            (9, 'Text mock 9'),
            (10, 'Text mock 10'),
            (11, 'Text mock 11');
        
        -- Обновляем sequence
        SELECT SETVAL('message_id_seq', (SELECT MAX(id) FROM message), TRUE);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
